version: '3'
volumes:
  vendor:
  node_modules:
services:
  nginx:
    depends_on:
      - api
      - web
    restart: always
    build:
      context: ./nginx
    ports:
      - '3050:80'
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - 9000:9000
    volumes:
      - ./api:/var/www/html
      - vendor:/var/www/html/vendor
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=admin
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - USER_PASSWORD=12345678
    depends_on:
      - db
  db:
    container_name: db
    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./api/storage/dbdata:/var/lib/mysql
  web:
    stdin_open: true
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    volumes:
      - node_modules:/app/node_modules
      - ./web:/app
    ports:
      - 8080:8080
    depends_on:
      - api