version: '3'
services:
  nginx:
    depends_on:
      - api
      # - web
    restart: always
    build:
      context: ./nginx
    ports:
      - '3050:80'
  web:
    stdin_open: true
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    volumes:
      - ./web/node_modules:/app/node_modules
      - ./web:/app
    ports:
      - 8080:8080
    depends_on:
      - api
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./api:/app
    depends_on:
      - db

  db:
    container_name: db
    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./api/storage/dbdata:/var/lib/mysql
