version: '3'
services:
  nginx:
    image: skipeverylunch/learnwithyou-nginx-10-14
    mem_limit: 128m
    hostname: nginx
    ports:
      - '80:80'
  api:
    image: skipeverylunch/learnwithyou-api-10-14
    mem_limit: 128m
    hostname: api
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=mysql
      - DB_PORT=$DB_PORT
      - DB_DATABASE=$DB_DATABASE
      - DB_USERNAME=$DB_USERNAME
      - DB_HOST=$DB_HOST
      - DB_PASSWORD=$DB_PASSWORD
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - USER_PASSWORD=$USER_PASSWORD
      - SESSION_DOMAIN=$APP_DOMAIN
      - SANCTUM_STATEFUL_DOMAINS=$WWW_APP_DOMAIN
  web:
    image: skipeverylunch/learnwithyou-web-10-14
    mem_limit: 128m
    hostname: web
