version: '3'
services:
  nginx:
    depends_on:
      - api
      - web
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - '3050:80'
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - 9000:9000
    volumes:
      - ./api:/app
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=admin
      - DB_USERNAME=root
      - DB_PASSWORD=rootpassword
      - USER_PASSWORD=12345678
    depends_on:
      - db
  db:
    container_name: db
    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpassword
      MYSQL_ROOT_PASSWORD: rootpassword
  web:
    stdin_open: true
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./web:/app
    ports:
      - 8080:8080
    environment:
      - USER_PASSWORD=12345678
    depends_on:
      - api
