version: '3'
services:
  nginx:
    depends_on:
      - api
      - web
    restart: always
    build:
      context: ./nginx
    ports:
      - '3050:80'
  api:
    build:
      context: ./api
    ports:
      - 8000:8000
    volumes:
      - ./api:/app
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=admin
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - db
  db:
    container_name: db
    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./api/storage/dbdata:/var/lib/mysql
  web:
    stdin_open: true
    build:
      context: ./web
    volumes:
      - /app/node_modules
      - ./web:/app
    ports:
      - 8080:8080
    depends_on:
      - api
