FROM php:7.4-fpm-alpine as builder

RUN docker-php-ext-install pdo pdo_mysql
RUN curl -sS https://getcomposer.org/installer | php -- \
        --install-dir=/usr/local/bin --filename=composer

WORKDIR /app
COPY . .
RUN composer install
# RUN php artisan migrate --seed
CMD php artisan serve --host=0.0.0.0 --port=9000

# FROM nginx
# EXPOSE 8000
# COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
# # COPY --from=builder /app/public /usr/share/nginx/html
# COPY --from=builder /app /usr/share/nginx/html